name: Good CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        uses: actions/npm-install@v1
        npm-version: '14.17.0'

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Deploy
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          DEPLOYMENT_PATH: ${{ secrets.DEPLOYMENT_PATH }}
        run: |
          rsync -avz --delete ./dist/ $USERNAME@$SERVER_IP:$DEPLOYMENT_PATH
